### PR TITLE
Add installation instructions to README.md

### LINKED ISSUE #13: How do you install?
There is no information about how this should be installed. It seems not to be packaged, which means a user must have more than casual knowledge on how CiviCRM internals work.

Could we at least have a section in the README about this?

### PR DESCRIPTION
**Pull request by thoni56**
This closes #13.

### CODE REVIEW

**Comment by eptbertram** [comment]
Just saw your change PR. The extension directory is called "ext". Maybe you like to update row 28? 
Unzip that into the extension directory (often `**custom_**ext` in the media directory or similar)

**Comment by thoni56** [comment]
In our installation it is called `custom_ext` and has been for 5 or 6 years ;-)

It seems the default has changed over the years. Just confirmed with a fresh install.

I'll reword.

**Comment by thoni56** [comment]
I've pushed a commit to update the README to point to `uplang` as it superseeds this extension.

**Comment by nganivet** [comment]
@thoni56 @eptbertram Merged and closed, thanks.

**Pull request merged**
